### ISSUE TITLE
请问怎么使用？

### ISSUE THREAD

**Issue by a18ccms** [ZNotify/android#30]
安装完APP。让设置ID。之后设置啥都是无效。具体如何使用呢？我用小米的手机。感谢。

**Comment by a18ccms** [comment]
你好。关于serve中的几个参数
`  WebSocketHost:
  FCM:
    FCMCredential: ""
  WebPush:
    VAPIDPrivateKey: ""
    VAPIDPublicKey: ""
  TelegramHost:
    BotToken: ""`
请问如何获取呢？最后能看出是电报机器人，第一个是Google的推送把？第二个是啥？我看帖子，不知道是不是你发的，说实现了小米的推送，请问是第二个吗？比较笨。。能写个大概的教程吗？完全么有头绪。docker架设上也不知道怎么填写参数。又怎么和这个notify app联动？

**Comment by Zxilly** [comment]
之前是实现了mipush，后来删除了，因为现在小米要求企业才能上架应用然后才能用mipush。
现在没有文档，具体的用法自己看代码吧。。。

**Comment by Zxilly** [comment]
https://github.com/ZNotify/android/commit/a3dca4114f12f9cb25ae318e1d6df93fcec9d585
如果你有小米应用商店的开发者账号，你把这个commit revert下就能有mipush支持了

**Comment by Zxilly** [comment]
你架设好自己的服务器之后按照这个
https://github.com/ZNotify/android#self-hosting
改一下重新编译就行。

**Comment by a18ccms** [comment]
感谢，我多研究研究代码~~
